In [3]:
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

ModuleNotFoundError: No module named 'tensorflow_hub'

In [2]:
image_path = '1.jpg'
image = Image.open(image_path)
original_image = np.array(image)

# Preprocess the image
input_image = tf.image.convert_image_dtype(original_image, dtype=tf.float32)
input_image = tf.image.resize(input_image, (513, 513))
input_image = input_image[tf.newaxis, :]

# Load the pre-trained DeepLabV3 model
model = tf.keras.applications.DenseNet121(include_top=False, weights='imagenet', input_tensor=input_image)

# Perform segmentation
predictions = model.predict(input_image)
predictions = tf.argmax(predictions, axis=-1)
predictions = predictions[0]

# Map the class labels to colors for visualization
def create_label_colormap():
    return np.array([
        [0, 0, 0],        # Background
        [128, 0, 0],      # Aeroplane
        [0, 128, 0],      # Bicycle
        # Add more classes as needed
    ])

def label_to_color_image(label):
    colormap = create_label_colormap()
    return colormap[label]

segmented_image = label_to_color_image(predictions.numpy().astype(np.uint8))

# Display the original and segmented images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(original_image)
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title('Segmented Image')
plt.imshow(segmented_image)
plt.axis('off')

plt.show()

ValueError: Found unexpected instance while processing input tensors for keras functional model. Expecting KerasTensor which is from tf.keras.Input() or output from keras layer call(). Got: [[[[0.10980393 0.1137255  0.12941177]
   [0.10588236 0.10980393 0.1254902 ]
   [0.10980393 0.1137255  0.12941177]
   ...
   [0.16696098 0.18264726 0.18205863]
   [0.17254902 0.18039216 0.1764706 ]
   [0.17480412 0.18264726 0.17088255]]

  [[0.10980393 0.1137255  0.12941177]
   [0.10588236 0.10980393 0.1254902 ]
   [0.10980393 0.1137255  0.12941177]
   ...
   [0.16284525 0.17853153 0.18814053]
   [0.17254902 0.1764706  0.19215688]
   [0.17519279 0.17911436 0.18911323]]

  [[0.10980393 0.1137255  0.12941177]
   [0.10588236 0.10980393 0.1254902 ]
   [0.10980393 0.1137255  0.12941177]
   ...
   [0.16197088 0.17765716 0.18942188]
   [0.17216107 0.17608264 0.18392578]
   [0.17209418 0.17601575 0.18385889]]

  ...

  [[0.16862746 0.17254902 0.19215688]
   [0.17134723 0.1752688  0.19095509]
   [0.16862746 0.17254902 0.18374583]
   ...
   [0.17254902 0.1764706  0.19215688]
   [0.17254902 0.1764706  0.18431373]
   [0.17254902 0.1764706  0.18431373]]

  [[0.16862746 0.17254902 0.19215688]
   [0.16813973 0.1698081  0.1950975 ]
   [0.17147097 0.17539254 0.18892273]
   ...
   [0.17539254 0.1793141  0.1950004 ]
   [0.17362708 0.17754865 0.18539178]
   [0.17274895 0.17667052 0.18451366]]

  [[0.16862746 0.17254902 0.18823531]
   [0.16862746 0.16944158 0.19837175]
   [0.17010266 0.17402422 0.18971051]
   ...
   [0.17254902 0.1764706  0.19215688]
   [0.1764706  0.18039216 0.18823531]
   [0.17266616 0.17658773 0.18443087]]]]